dist: trusty
sudo: false
language: cpp
os: linux

matrix:
  include:
    - env: COMPILER=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

    - env: COMPILER=clang++-6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-6
          packages:
            - clang-6

    - env:
      - COMPILER=clang++-7
      - EXERCISM_COMMON_CATCH=false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7

    - env: COMPILER=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8

before_install:
  - sudo add-apt-repository -y ppa:samuel-bachmann/boost
  - sudo apt-get -y -d update
install:
  - sudo apt-get -y install cmake3 ninja-build libboost-date-time1.60-dev
  - export CXX=${COMPILER}
  - ${CXX} --version
script:
  - bin/fetch-configlet
  - bin/configlet lint .
  - bin/check-configlet-fmt.sh
  - bin/check-exercises.sh
